### ISSUE TITLE
Endless loop / fork bomb

### ISSUE THREAD

**Issue by carpikes** [rdnetto/YCM-Generator#55]
Hi, I'm having some trouble while trying to generate the ycm config file for mangos ( https://github.com/mangostwo/server.git ) which is using the ACE C++ framework. 
Basically, it start forking until all system resources are exausted. 

```
$ cd /home/al/git/other/mangos-server
$ ~/.vim/bundle/YCM-Generator/config_gen.py . --verbose
Running cmake in '/tmp/tmpjgQglj'...
$ cmake /home/al/git/other/mangos-server
-- The C compiler identification is Clang 3.8.0
-- The CXX compiler identification is Clang 3.8.0
-- Check for working C compiler: /home/al/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang
-- Check for working C compiler: /home/al/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/al/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang++
-- Check for working CXX compiler: /home/al/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

This script builds the MaNGOS server.
  Options that can be used in order to configure the process:
    CMAKE_INSTALL_PREFIX    Path where the server should be installed to
    CMAKE_BUILD_TYPE        Sets build type (Release;Debug;...)
    PCH                     Use precompiled headers
    INCLUDE_BINDINGS_DIR    Include a script library in src/bindings/ with the
                            defined name. the name must corespond to the name of
                            the folder and the folder must contain a valid
                            CMakeLists.txt
    ACE_USE_EXTERNAL        Use external ACE
    BUILD_SCRIPTS           Build server scripts content.
    POSTGRESQL              Use PostgreSQL bindings.
  To set an option simply type -D<OPTION>=<VALUE> after 'cmake <srcs>'.
  Also, you can specify the generator with -G. see 'cmake --help' for more details
  For example: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/mangos

-- Detected 64-bit platform.
-- Found Git: /usr/bin/git  
-- Using mysql-config: /usr/bin/mysql_config
-- Found MySQL library: /usr/lib64/libmysqlclient.so
-- Found MySQL headers: /usr/include/mysql
-- Found OpenSSL library: /usr/lib64/libssl.so
-- Found OpenSSL headers: /usr/include/openssl
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- MaNGOS-Core revision  : b8ce9508483375a36699c309bce36810c4548007
-- Install server to     : /usr/local
-- Use PCH               : No
CMake Warning (dev) at CMakeLists.txt:300 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "genrev".  Use the
  target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at src/framework/CMakeLists.txt:86 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "TBB_Project" of target "framework" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /tmp/tmpjgQglj

Running make...
$ make -i -j4
Scanning dependencies of target ACE_Project
Scanning dependencies of target genrev
Scanning dependencies of target detour
Scanning dependencies of target g3dlite
[  1%] [  1%] Creating directories for 'ACE_Project'
Building CXX object CMakeFiles/genrev.dir/src/tools/genrevision/genrevision.cpp.o
[  1%] Linking CXX executable genrev
Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourAlloc.cpp.o
[  1%] [  1%] Built target genrev
Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourCommon.cpp.o
Scanning dependencies of target gsoap
[  1%] Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourNavMeshBuilder.cpp.o
[  1%] [  1%] [  1%] Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourNavMesh.cpp.o
No download step for 'ACE_Project'
Building CXX object dep/src/gsoap/CMakeFiles/gsoap.dir/stdsoap2.cpp.o
[  1%] Linking CXX static library libgsoap.a
Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourNavMeshQuery.cpp.o
[  1%] [  1%] No patch step for 'ACE_Project'
/usr/bin/ranlib: 'libgsoap.a': No such file
Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourNode.cpp.o
[  1%] [  1%] Built target gsoap
[  2%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/AABox.cpp.o
Building CXX object dep/recastnavigation/Detour/Source/CMakeFiles/detour.dir/DetourObstacleAvoidance.cpp.o
[  2%] [  2%] Scanning dependencies of target revision.h
No update step for 'ACE_Project'
make[2]: *** No rule to make target 'genrev', needed by 'CMakeFiles/revision.h'.  Stop.
Linking CXX static library libdetour.a
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Any.cpp.o
[  2%] [  2%] Built target revision.h
[  2%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/BinaryFormat.cpp.o
[  2%] /usr/bin/ranlib: 'libdetour.a': No such file
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/BinaryInput.cpp.o
Performing configure step for 'ACE_Project'
[  3%] [  3%] Built target detour
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/BinaryOutput.cpp.o
[  3%] [  3%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Capsule.cpp.o
[  3%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Box.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/CollisionDetection.cpp.o
[  3%] [  3%] [  3%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Crypto.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/CoordinateFrame.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Cylinder.cpp.o
[  3%] [  4%] [  4%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/FileSystem.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/LineSegment.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Line.cpp.o
[  4%] [  4%] [  4%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Log.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Matrix3.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Matrix4.cpp.o
[  4%] [  4%] [  5%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/MemoryManager.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/PhysicsFrame.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Plane.cpp.o
[  5%] [  5%] [  5%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Random.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Ray.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Quat.cpp.o
checking build system type... [  5%] [  5%] [  5%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/ReferenceCount.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/RegistryUtil.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Sphere.cpp.o
[  6%] [  6%] [  6%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/System.cpp.o
x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/TextOutput.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/TextInput.cpp.o
/usr/bin/install -c
checking whether build environment is sane... [  6%] [  6%] [  6%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Triangle.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/UprightFrame.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Vector2.cpp.o
[  6%] [  7%] [  7%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Vector3.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/Vector4.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/debugAssert.cpp.o
[  7%] [  7%] [  7%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/fileutils.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/format.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/g3dfnmatch.cpp.o
[  7%] [  7%] [  7%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/g3dmath.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/stringutils.cpp.o
Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/prompt.cpp.o
[  8%] Building CXX object dep/src/g3dlite/CMakeFiles/g3dlite.dir/uint128.cpp.o
Linking CXX static library libg3dlite.a
/usr/bin/ranlib: 'libg3dlite.a': No such file
[  8%] Built target g3dlite
yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether #! works in shell scripts... yes
checking whether the C++ compiler works... no
configure: error: in `/tmp/tmpjgQglj/dep/ACE_wrappers':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
[  9%] Performing build step for 'ACE_Project'
[100%] Performing build step for 'ACE_Project'
[100%] Performing build step for 'ACE_Project'
[100%] Performing build step for 'ACE_Project'
[100%] Performing build step for 'ACE_Project'
[... endless ...]
^CTraceback (most recent call last):
  File "/home/al/.vim/bundle/YCM-Generator/config_gen.py", line 460, in <module>
    sys.exit(main())
  File "/home/al/.vim/bundle/YCM-Generator/config_gen.py", line 107, in main
    fake_build(project_dir, c_build_log.name, cxx_build_log.name, **args)
  File "/home/al/.vim/bundle/YCM-Generator/config_gen.py", line 224, in fake_build
    run(make_args, env=env, **proc_opts)
  File "/home/al/.vim/bundle/YCM-Generator/config_gen.py", line 198, in run
    subprocess.call(cmd, *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

**Comment by rdnetto** [comment]
`ps aux` shows the following repeating set of processes:

```
reuben   17337  0.0  0.0   6708  2004 pts/4    S+   14:03   0:00 make
reuben   17342  0.0  0.0  20324  3016 pts/4    S+   14:03   0:00 /bin/sh -c cd /tmp/tmpa3c6ps && make -f CMakeFiles/Makefile2 dep/ACE_wrappers/all
reuben   17343  0.0  0.0   6684  1964 pts/4    S+   14:03   0:00 make -f CMakeFiles/Makefile2 dep/ACE_wrappers/all
reuben   17347  0.0  0.0   6684  1936 pts/4    S+   14:03   0:00 make -f dep/ACE_wrappers/CMakeFiles/ACE_Project.dir/build.make dep/ACE_wrappers/CMakeFiles/A
reuben   17349  0.0  0.0  20324  3076 pts/4    S+   14:03   0:00 /bin/sh -c cd /tmp/tmpa3c6ps/dep/ACE_wrappers && make
```

which indicates there's some kind of infinite loop in the makefiles. I suspect there's some section of the build system which assumes a file will be created by a previous section and recurses unboundedly if it does not.

I've checked, and none of the scripts in `fake-toolchain` are being called during that loop, so it's not as simple as an operation being retried repeatedly because it failed. This also means that we can't work around it by patching one of them.

This section of output caught my eye:

```
[  7%] Built target g3dlite
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking whether #! works in shell scripts... yes
checking whether the C++ compiler works... no
configure: error: in `/tmp/tmpnxU6wK/dep/ACE_wrappers':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
[  8%] Performing build step for 'ACE_Project'
[100%] Performing build step for 'ACE_Project'
```

That means that `./configure` is being run inside the make section, which is a problem. YCM-Gen uses a slightly different setup for the config and build stages, because autotools, etc. actually need to compile programs to determine their behaviour, but we don't normally wish to compile programs in the build stage as it increases the generation time too much.

You can work around this by deleting all the files in `fake-toolchain/Unix`that are symlinked to `true`, then adding `/usr/bin/clang $@` to the else-block in `cc` (and similarly `/usr/bin/clang++ $@` for `cxx`). This changes the behaviour to always run the compiler. On my system, it produced the following flags (where `/tmp/mnt/server` is the source directory):

```
flags = [
    '-x',
    'c++',
    '-DACE_BUILD_DLL',
    '-DACE_ETCL_BUILD_DLL',
    '-DACE_SSL_BUILD_DLL',
    '-DDO_MYSQL',
    '-DETCL_PARSER_BUILD_DLL',
    '-DHAVE_CONFIG_H',
    '-DMONITOR_CONTROL_BUILD_DLL',
    '-DPIC',
    '-DSYSCONFDIR="/usr/local/etc/"',
    '-DVERSION="0.18.1"',
    '-Dmangosscript_EXPORTS',
    '-I.',
    '-I..',
    '-I../..',
    '-I/tmp/mnt/server/dep/ACE_wrappers',
    '-I/tmp/mnt/server/dep/include',
    '-I/tmp/mnt/server/dep/include/g3dlite',
    '-I/tmp/mnt/server/dep/include/gsoap',
    '-I/tmp/mnt/server/dep/include/zlib',
    '-I/tmp/mnt/server/dep/recastnavigation',
    '-I/tmp/mnt/server/dep/recastnavigation/Detour',
    '-I/tmp/mnt/server/dep/recastnavigation/Detour/Include',
    '-I/tmp/mnt/server/dep/recastnavigation/Detour/Source',
    '-I/tmp/mnt/server/dep/src/g3dlite',
    '-I/tmp/mnt/server/dep/src/gsoap',
    '-I/tmp/mnt/server/src/framework',
    '-I/tmp/mnt/server/src/game',
    '-I/tmp/mnt/server/src/game/AuctionHouseBot',
    '-I/tmp/mnt/server/src/game/BattleGround',
    '-I/tmp/mnt/server/src/game/OutdoorPvP',
    '-I/tmp/mnt/server/src/game/vmap',
    '-I/tmp/mnt/server/src/scripts/base',
    '-I/tmp/mnt/server/src/scripts/include',
    '-I/tmp/mnt/server/src/shared',
    '-I/tmp/tmpJxGcEX',
    '-I/tmp/tmpJxGcEX/src/shared',
    '-I/usr/include/mysql',
    '-I/usr/include/openssl',
    '-I/usr/kerberos/include',
    '-I/usr/local/include',
    '-I/usr/local/kerberos/include',
    '-W',
    '-Wall',
    '-Werror',
    '-Wpointer-arith',
    '-nostdlib',
]
```

(You can undo the workaround by running `git reset --hard` in YCM-Gen's directory.)

**Comment by carpikes** [comment]
Thanks, it worked! :)
